// Auto-generated by tools/convert_autoencoder.py — do not edit.
#pragma once

// Threshold = 99-th percentile of reconstruction MSE on the
// training set; the firmware trips an anomaly when the live
// reconstruction MSE exceeds this value.
constexpr float kAnomalyThreshold = 0.0313432105f;
constexpr int   kAEInputDim = 256;
constexpr int   kAENumChannels = 8;
constexpr int   kAESeqLen = 32;
