/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``{"status": "ok"}`` when the process is alive.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version metadata */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List piles
         * @description Return all piles, with optional region / operator / status filters.
         */
        get: operations["list_piles_api_piles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{pile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pile detail
         * @description Return a single pile with its 24-hour rolling summary.
         */
        get: operations["get_pile_api_piles__pile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{pile_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pile telemetry (history)
         * @description Return historical telemetry for a single pile, newest first.
         */
        get: operations["get_telemetry_api_piles__pile_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operators
         * @description Return all operators with their pile counts.
         */
        get: operations["list_operators_api_operators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List regions */
        get: operations["list_regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Pile Id */
            pile_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Type
             * @enum {string}
             */
            type: "voltage_anomaly" | "thermal_fault" | "vibration_event" | "cable_fault" | "communication_loss" | "charging_start" | "charging_end";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Message */
            message: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Resolved */
            resolved: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OperatorOut */
        OperatorOut: {
            /**
             * Id
             * @description Operator slug, e.g. 'state_grid'.
             */
            id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Market Share */
            market_share: number;
            /** Color */
            color: string;
            /**
             * Pile Count
             * @description Number of piles owned.
             */
            pile_count?: number | null;
        };
        /** PileDetail */
        PileDetail: {
            /** Id */
            id: string;
            /** Operator Id */
            operator_id: string;
            /** Region Id */
            region_id: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Capacity Kw */
            capacity_kw: number;
            /** Connector Type */
            connector_type: string;
            /**
             * Installed At
             * Format: date-time
             */
            installed_at: string;
            /** Subsidy Amount */
            subsidy_amount: number;
            /**
             * Subsidy Group
             * @enum {string}
             */
            subsidy_group: "treatment" | "control";
            /**
             * Current Status
             * @enum {string}
             */
            current_status: "idle" | "charging" | "occupied" | "fault" | "offline";
            /** Current Voltage */
            current_voltage: number;
            /** Current Current */
            current_current: number;
            /** Current Power */
            current_power: number;
            /** Current Occupancy */
            current_occupancy: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            summary_24h: components["schemas"]["PileSummary24h"];
        };
        /** PileOut */
        PileOut: {
            /** Id */
            id: string;
            /** Operator Id */
            operator_id: string;
            /** Region Id */
            region_id: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Capacity Kw */
            capacity_kw: number;
            /** Connector Type */
            connector_type: string;
            /**
             * Installed At
             * Format: date-time
             */
            installed_at: string;
            /** Subsidy Amount */
            subsidy_amount: number;
            /**
             * Subsidy Group
             * @enum {string}
             */
            subsidy_group: "treatment" | "control";
            /**
             * Current Status
             * @enum {string}
             */
            current_status: "idle" | "charging" | "occupied" | "fault" | "offline";
            /** Current Voltage */
            current_voltage: number;
            /** Current Current */
            current_current: number;
            /** Current Power */
            current_power: number;
            /** Current Occupancy */
            current_occupancy: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** PileSummary24h */
        PileSummary24h: {
            /** Avg Occupancy */
            avg_occupancy: number;
            /** Peak Occupancy */
            peak_occupancy: number;
            /** Total Energy Kwh */
            total_energy_kwh: number;
            /** Fault Count */
            fault_count: number;
            /** Sample Count */
            sample_count: number;
        };
        /** RegionOut */
        RegionOut: {
            /** Id */
            id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Radius Km */
            radius_km: number;
            /** Description */
            description: string;
            /** Pile Count */
            pile_count?: number | null;
        };
        /** TelemetryPoint */
        TelemetryPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Voltage */
            voltage: number;
            /** Current */
            current: number;
            /** Power */
            power: number;
            /** Occupancy Rate */
            occupancy_rate: number;
            /** Energy Delivered Kwh */
            energy_delivered_kwh: number;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "charging" | "occupied" | "fault" | "offline";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_piles_api_piles_get: {
        parameters: {
            query?: {
                /** @description Filter by region id. */
                region?: string | null;
                /** @description Filter by operator id. */
                operator?: string | null;
                /** @description Filter by current_status. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pile_api_piles__pile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_api_piles__pile_id__telemetry_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                pile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operators_api_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"][];
                };
            };
        };
    };
    list_regions_api_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                /** @description Filter by event type. */
                type?: string | null;
                /** @description Filter by severity. */
                severity?: string | null;
                /** @description Filter by pile id. */
                pile_id?: string | null;
                /** @description Only events on/after this UTC ts. */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
