/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``{"status": "ok"}`` when the process is alive.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version metadata */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List piles
         * @description Return all piles, with optional region / operator / status filters.
         */
        get: operations["list_piles_api_piles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{pile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pile detail
         * @description Return a single pile with its 24-hour rolling summary.
         */
        get: operations["get_pile_api_piles__pile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/piles/{pile_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pile telemetry (history)
         * @description Return historical telemetry for a single pile, newest first.
         */
        get: operations["get_telemetry_api_piles__pile_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operators
         * @description Return all operators with their pile counts.
         */
        get: operations["list_operators_api_operators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List regions */
        get: operations["list_regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/utilization-24h": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Citywide hourly utilization for the last 24 hours
         * @description Return 24 hourly buckets of average occupancy across all piles.
         *
         *     Used by the IOC homepage bottom-strip line chart. Each bucket is an
         *     hour-of-day (0-23 UTC); the value is the mean occupancy across all
         *     telemetry rows in the last 24h that fell into that hour.
         */
        get: operations["utilization_24h_api_stats_utilization_24h_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/fault-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fault-type distribution over a recent window
         * @description Return event counts grouped by type (fault categories only).
         *
         *     Charging start/end and communication-loss are excluded; we want the
         *     "what's actually breaking" view for the bottom-strip donut chart.
         */
        get: operations["fault_types_api_stats_fault_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/predict/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LSTM demand prediction */
        post: operations["predict_demand_api_ai_predict_demand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/predict/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** XGBoost + SHAP site selection */
        post: operations["predict_site_api_ai_predict_site_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/anomaly/{pile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autoencoder anomaly check */
        get: operations["check_anomaly_api_ai_anomaly__pile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/yolo/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** YOLOv8 occupancy detection */
        post: operations["yolo_detect_api_ai_yolo_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyResponse */
        AnomalyResponse: {
            /** Pile Id */
            pile_id: string;
            /** Is Anomaly */
            is_anomaly: boolean;
            /** Reconstruction Error */
            reconstruction_error: number;
            /** Threshold */
            threshold: number;
            /** Margin Ratio */
            margin_ratio: number;
        };
        /** Body_yolo_detect_api_ai_yolo_detect_post */
        Body_yolo_detect_api_ai_yolo_detect_post: {
            /**
             * Image
             * Format: binary
             * @description JPEG / PNG image of a parking area.
             */
            image: string;
        };
        /** DemandRequest */
        DemandRequest: {
            /**
             * Pile Id
             * @description Pile id (must exist in the DB).
             */
            pile_id: string;
            /**
             * Hours Ahead
             * @description Forecast horizon in hours.
             * @default 1
             */
            hours_ahead: number;
        };
        /** DemandResponse */
        DemandResponse: {
            /** Pile Id */
            pile_id: string;
            /** Hours Ahead */
            hours_ahead: number;
            /** Predicted Occupancy */
            predicted_occupancy: number;
            /** Std */
            std: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Pile Id */
            pile_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Type
             * @enum {string}
             */
            type: "voltage_anomaly" | "thermal_fault" | "vibration_event" | "cable_fault" | "communication_loss" | "charging_start" | "charging_end";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Message */
            message: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Resolved */
            resolved: boolean;
        };
        /** FaultTypeBucket */
        FaultTypeBucket: {
            /** Type */
            type: string;
            /** Count */
            count: number;
            /** Severity Breakdown */
            severity_breakdown: {
                [key: string]: number;
            };
        };
        /** FaultTypesResponse */
        FaultTypesResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Window Hours */
            window_hours: number;
            /** Total */
            total: number;
            /** Buckets */
            buckets: components["schemas"]["FaultTypeBucket"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyOccupancy */
        HourlyOccupancy: {
            /**
             * Hour
             * @description Hour of day, 0-23 in UTC.
             */
            hour: number;
            /** Avg Occupancy */
            avg_occupancy: number;
            /** Sample Count */
            sample_count: number;
        };
        /** OperatorOut */
        OperatorOut: {
            /**
             * Id
             * @description Operator slug, e.g. 'state_grid'.
             */
            id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Market Share */
            market_share: number;
            /** Color */
            color: string;
            /**
             * Pile Count
             * @description Number of piles owned.
             */
            pile_count?: number | null;
        };
        /** PileDetail */
        PileDetail: {
            /** Id */
            id: string;
            /** Operator Id */
            operator_id: string;
            /** Region Id */
            region_id: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Capacity Kw */
            capacity_kw: number;
            /** Connector Type */
            connector_type: string;
            /**
             * Installed At
             * Format: date-time
             */
            installed_at: string;
            /** Subsidy Amount */
            subsidy_amount: number;
            /**
             * Subsidy Group
             * @enum {string}
             */
            subsidy_group: "treatment" | "control";
            /**
             * Current Status
             * @enum {string}
             */
            current_status: "idle" | "charging" | "occupied" | "fault" | "offline";
            /** Current Voltage */
            current_voltage: number;
            /** Current Current */
            current_current: number;
            /** Current Power */
            current_power: number;
            /** Current Occupancy */
            current_occupancy: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            summary_24h: components["schemas"]["PileSummary24h"];
        };
        /** PileOut */
        PileOut: {
            /** Id */
            id: string;
            /** Operator Id */
            operator_id: string;
            /** Region Id */
            region_id: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Capacity Kw */
            capacity_kw: number;
            /** Connector Type */
            connector_type: string;
            /**
             * Installed At
             * Format: date-time
             */
            installed_at: string;
            /** Subsidy Amount */
            subsidy_amount: number;
            /**
             * Subsidy Group
             * @enum {string}
             */
            subsidy_group: "treatment" | "control";
            /**
             * Current Status
             * @enum {string}
             */
            current_status: "idle" | "charging" | "occupied" | "fault" | "offline";
            /** Current Voltage */
            current_voltage: number;
            /** Current Current */
            current_current: number;
            /** Current Power */
            current_power: number;
            /** Current Occupancy */
            current_occupancy: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** PileSummary24h */
        PileSummary24h: {
            /** Avg Occupancy */
            avg_occupancy: number;
            /** Peak Occupancy */
            peak_occupancy: number;
            /** Total Energy Kwh */
            total_energy_kwh: number;
            /** Fault Count */
            fault_count: number;
            /** Sample Count */
            sample_count: number;
        };
        /** RegionOut */
        RegionOut: {
            /** Id */
            id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Center Lat */
            center_lat: number;
            /** Center Lng */
            center_lng: number;
            /** Radius Km */
            radius_km: number;
            /** Description */
            description: string;
            /** Pile Count */
            pile_count?: number | null;
        };
        /** ShapContributionOut */
        ShapContributionOut: {
            /** Feature */
            feature: string;
            /** Value */
            value: number;
            /** Shap Contribution */
            shap_contribution: number;
        };
        /**
         * SiteFeatures
         * @description Pydantic input for the API endpoint.
         *
         *     Used both as the FastAPI request schema and as the source for
         *     :func:`features_to_vector`.
         */
        SiteFeatures: {
            /**
             * Lat
             * @description Latitude (杭州 ~30.x).
             */
            lat: number;
            /**
             * Lng
             * @description Longitude (杭州 ~120.x).
             */
            lng: number;
            /**
             * Pop Density 1Km
             * @description People per km² in 1 km radius.
             */
            pop_density_1km: number;
            /** Poi Mall Count */
            poi_mall_count: number;
            /** Poi Office Count */
            poi_office_count: number;
            /** Poi Residential Count */
            poi_residential_count: number;
            /** Existing Pile Count 1Km */
            existing_pile_count_1km: number;
            /** Avg Utilization 1Km */
            avg_utilization_1km: number;
            /**
             * Road Grade
             * @description 1=支路 / 2=次干道 / 3=主干道
             */
            road_grade: number;
            /**
             * Operator
             * @description Operator slug — one of state_grid/teld/starcharge/nio.
             * @default state_grid
             */
            operator: string;
        };
        /** SiteResponse */
        SiteResponse: {
            /** Predicted Utilization 6M */
            predicted_utilization_6m: number;
            /** Confidence Interval 95 */
            confidence_interval_95: [
                number,
                number
            ];
            /** Shap Top3 */
            shap_top3: components["schemas"]["ShapContributionOut"][];
            /** Shap Base Value */
            shap_base_value: number;
        };
        /** TelemetryPoint */
        TelemetryPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Voltage */
            voltage: number;
            /** Current */
            current: number;
            /** Power */
            power: number;
            /** Occupancy Rate */
            occupancy_rate: number;
            /** Energy Delivered Kwh */
            energy_delivered_kwh: number;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "charging" | "occupied" | "fault" | "offline";
        };
        /** Utilization24hResponse */
        Utilization24hResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Hourly */
            hourly: components["schemas"]["HourlyOccupancy"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YoloBox */
        YoloBox: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
            /** Confidence */
            confidence: number;
            /** Class Name */
            class_name: string;
        };
        /** YoloResponse */
        YoloResponse: {
            /** Vehicle Count */
            vehicle_count: number;
            /** Boxes */
            boxes: components["schemas"]["YoloBox"][];
            /** Image Width */
            image_width: number;
            /** Image Height */
            image_height: number;
            /** Inference Ms */
            inference_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_piles_api_piles_get: {
        parameters: {
            query?: {
                /** @description Filter by region id. */
                region?: string | null;
                /** @description Filter by operator id. */
                operator?: string | null;
                /** @description Filter by current_status. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pile_api_piles__pile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_api_piles__pile_id__telemetry_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                pile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operators_api_operators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorOut"][];
                };
            };
        };
    };
    list_regions_api_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                /** @description Filter by event type. */
                type?: string | null;
                /** @description Filter by severity. */
                severity?: string | null;
                /** @description Filter by pile id. */
                pile_id?: string | null;
                /** @description Only events on/after this UTC ts. */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    utilization_24h_api_stats_utilization_24h_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Utilization24hResponse"];
                };
            };
        };
    };
    fault_types_api_stats_fault_types_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultTypesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_demand_api_ai_predict_demand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_site_api_ai_predict_site_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteFeatures"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_anomaly_api_ai_anomaly__pile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yolo_detect_api_ai_yolo_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_yolo_detect_api_ai_yolo_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YoloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
