"""Convert the Spawn-4 PyTorch Autoencoder to a TFLite model for ESP32.

Bypasses onnx2tf dependency hell by rebuilding the (very simple) MLP in Keras
directly and copying weights tensor-by-tensor.

Run with Python 3.13 (3.14 has no TF wheels yet):

    python3.13 firmware/pile-simulator/tools/convert_autoencoder.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Silence TF logs.
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import numpy as np
import tensorflow as tf
import torch

REPO_ROOT  = Path(__file__).resolve().parents[3]
PT_PATH    = REPO_ROOT / "backend/ai/anomaly_detection/saved/autoencoder.pt"
TFLITE_OUT = REPO_ROOT / "backend/ai/anomaly_detection/saved/autoencoder.tflite"
HEADER_OUT = REPO_ROOT / "firmware/pile-simulator/include/autoencoder_model.h"
META_OUT   = REPO_ROOT / "firmware/pile-simulator/include/autoencoder_meta.h"

INPUT_DIM = 256


def build_keras(state_dict: dict) -> tf.keras.Model:
    """Construct a Keras model with the same shape and copy PyTorch weights."""
    inputs = tf.keras.Input(shape=(INPUT_DIM,), name="x_flat")
    x = tf.keras.layers.Dense(256, activation="relu")(inputs)
    x = tf.keras.layers.Dense(16,  activation="relu")(x)
    x = tf.keras.layers.Dense(256, activation="relu")(x)
    outputs = tf.keras.layers.Dense(INPUT_DIM, name="recon_flat")(x)
    model = tf.keras.Model(inputs, outputs)

    # Map: encoder.0 → dense_0, encoder.2 → dense_1,
    #      decoder.0 → dense_2, decoder.2 → dense_3
    pt_layer_keys = [
        ("encoder.0.weight", "encoder.0.bias"),
        ("encoder.2.weight", "encoder.2.bias"),
        ("decoder.0.weight", "decoder.0.bias"),
        ("decoder.2.weight", "decoder.2.bias"),
    ]
    keras_dense = [l for l in model.layers if isinstance(l, tf.keras.layers.Dense)]
    assert len(keras_dense) == len(pt_layer_keys), "layer count mismatch"

    for kl, (wk, bk) in zip(keras_dense, pt_layer_keys):
        # PyTorch Linear weight shape: (out_dim, in_dim).  Keras Dense kernel
        # shape: (in_dim, out_dim) — transpose.
        w = state_dict[wk].cpu().numpy().T.astype(np.float32)
        b = state_dict[bk].cpu().numpy().astype(np.float32)
        kl.set_weights([w, b])
    return model


def numerical_check(model: tf.keras.Model, state_dict: dict) -> float:
    """Run identical input through PyTorch + Keras and report max abs diff."""
    rng = np.random.default_rng(seed=42)
    x = rng.standard_normal((4, INPUT_DIM)).astype(np.float32)

    # PyTorch reference forward.
    with torch.no_grad():
        h = torch.from_numpy(x)
        for k, b in [("encoder.0", "encoder.0.bias"),
                     ("encoder.2", "encoder.2.bias"),
                     ("decoder.0", "decoder.0.bias")]:
            w = state_dict[f"{k}.weight"]
            bias = state_dict[b]
            h = torch.relu(torch.nn.functional.linear(h, w, bias))
        # Final layer (no ReLU? Inspecting: spec says decoder.2 has no
        # activation, but the saved state has 4 Linear with ReLU between
        # all 3 internal — same as encoder side).  However the original
        # PileAutoencoder.forward applies ReLU between all internal layers
        # but NOT after the last decoder layer.  Match that.
        h = torch.nn.functional.linear(
            h, state_dict["decoder.2.weight"], state_dict["decoder.2.bias"]
        )
    pt_out = h.numpy()

    # Keras forward.
    keras_out = model(x).numpy()
    diff = float(np.max(np.abs(pt_out - keras_out)))
    return diff


def convert_tflite(model: tf.keras.Model) -> bytes:
    """Convert to TFLite (float32, no quantization — simplest path)."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]   # weight-only quant
    return converter.convert()


def write_c_header(tflite_bytes: bytes, threshold: float) -> None:
    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    # xxd-style header.
    arr_name = "autoencoder_model_data"
    lines = [
        "// Auto-generated by tools/convert_autoencoder.py — do not edit.",
        "// Source: backend/ai/anomaly_detection/saved/autoencoder.pt",
        "//",
        "// PileAutoencoder weights baked as TFLite flatbuffer for TFLM.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"constexpr unsigned int {arr_name}_len = {len(tflite_bytes)};",
        f"alignas(8) const unsigned char {arr_name}[] = {{",
    ]
    hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
    for i in range(0, len(hex_bytes), 12):
        chunk = ", ".join(hex_bytes[i : i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    HEADER_OUT.write_text("\n".join(lines) + "\n")

    META_OUT.write_text(
        "// Auto-generated by tools/convert_autoencoder.py — do not edit.\n"
        "#pragma once\n\n"
        "// Threshold = 99-th percentile of reconstruction MSE on the\n"
        "// training set; the firmware trips an anomaly when the live\n"
        "// reconstruction MSE exceeds this value.\n"
        f"constexpr float kAnomalyThreshold = {threshold:.10f}f;\n"
        "constexpr int   kAEInputDim = 256;\n"
        "constexpr int   kAENumChannels = 8;\n"
        "constexpr int   kAESeqLen = 32;\n"
    )


def main() -> int:
    print(f"[convert] loading {PT_PATH}")
    ckpt = torch.load(PT_PATH, map_location="cpu", weights_only=False)
    sd = ckpt["state_dict"]
    threshold = float(ckpt.get("threshold_99", ckpt.get("threshold", 0.05)))

    print("[convert] building Keras mirror + copying weights")
    model = build_keras(sd)

    diff = numerical_check(model, sd)
    print(f"[convert] PyTorch vs Keras max |Δ|: {diff:.2e}")
    if diff > 1e-4:
        print("WARN: numerical drift > 1e-4 — investigate weight transpose.")

    print("[convert] converting Keras → TFLite (default optimisations)")
    tflite = convert_tflite(model)
    TFLITE_OUT.write_bytes(tflite)
    print(f"[convert] wrote {TFLITE_OUT} ({len(tflite)} bytes)")

    write_c_header(tflite, threshold)
    print(f"[convert] wrote {HEADER_OUT}")
    print(f"[convert] wrote {META_OUT} (threshold={threshold:.6f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
